dist: xenial
language: python
sudo: false

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - 3.9-dev

env:
  global:
    - PURE_EVAL_SLOW_TESTS=1
    - COVERALLS_PARALLEL=true

before_install:
  - pip install --upgrade coveralls setuptools setuptools_scm pep517

install:
  - pip install ".[tests]"

script:
  - coverage run --branch --include='pure_eval/*' -m pytest --junitxml=./rspec.xml
  - coverage report -m

after_success:
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook
  email: false
